[pytest]
markers =
    delete_address: mark test as one that deletes an address
    delete_product: mark test as one that deletes a product
    delete_card: mark test as one that deletes a card
    screenshot: mark test as one that makes a screenshot
    video: mark test as one that records a video
    isolated: tests that must run separately
    smoke: mark test as smoke

pythonpath = .